### ISSUE TITLE
Running storybook fails

### ISSUE THREAD

**Issue by ErezBiren** [ealush/emoji-picker-react#345]
I tried to run "yarn storybook" and got  this error:

```shell
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\git\emoji-picker-react\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\git\emoji-picker-react\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\git\emoji-picker-react\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\git\emoji-picker-react\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\git\emoji-picker-react\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\git\emoji-picker-react\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\git\emoji-picker-react\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at C:\git\emoji-picker-react\node_modules\loader-runner\lib\LoaderRunner.js:205:4 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

I had to change the package.json file `storybook` script 

from:
``` json 
"storybook": "start-storybook -p 6006",
```

to:
``` json 
"storybook": "SET NODE_OPTIONS=--openssl-legacy-provider && start-storybook -p 6006",
```

Are you familiar with that issue? 
Is that supposed to be a permanent solution? if so, I can PR it.

**Comment by shootermv** [comment]
i found kind a workaround after lookin [here](https://github.com/storybookjs/storybook/issues/16555)
`export NODE_OPTIONS=--openssl-legacy-provider && yarn storybook`
but, i think there is more elegant solution exist...

**Comment by shootermv** [comment]
will it help for this issue - to upgrade storybook to latest v7.4.5  version?
